### ISSUE TITLE
pkgdown yaml

### ISSUE THREAD

**Issue by strengejacke** [easystats/easystats#203]
@IndrajeetPatil I'm not sure what these lines in `_pkgdown.yml` in our packages do, in particular `opengraph`. For _performance_ or _parameters_, there is no image at `man/figures/card.png`.

```
template:
  bootstrap: 5
  bootswatch: Superhero
  opengraph:
    image:
      src: man/figures/card.png
    twitter:
      creator: "@easystats4u"
      card: summary_large_image
```
