### ISSUE TITLE
Follow recommended `{pkgdown}` workflow for using template packages

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#264]
In https://github.com/easystats/easystats/issues/186, we started using template package to build websites, but the workflow I implemented is not standard.

As mentioned [here](https://pkgdown.r-lib.org/articles/customise.html#template-packages), to implement the recommended workflow, you need to make the following changes.

- **Add** this to the end of `DESCRIPTION`:

```dcf
Config/Needs/website:
    rstudio/bslib,
    r-lib/pkgdown,
    easystats/easystatstemplate
```

- **Remove** `r-lib/pkgdown` and `easystats/easystatstemplate` from `.github/workflows/pkgdown.yml`:

```yaml
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
              local::.
              r-lib/pkgdown
              easystats/easystatstemplate
          needs: website
```

- This is optional, but I personally prefer to always build the website with the latest version of `pandoc` (change in file `.github/workflows/pkgdown.yml`):

```yaml
      - uses: r-lib/actions/setup-pandoc@v2
        with:
            pandoc-version: '2.19.1'
```

# Progress tracker

- [x] insight 
- [x] modelbased
- [x] bayestestR
- [x] effectsize
- [x] parameters
- [x] performance
- [x] correlation
- [x] report
- [x] see
- [x] datawizard
- [x] easystats
